main_dir: ''
data:
  name: 'openloop'
  train_data_dir: "data/train"
  test_data_dir: "data/test_minimal"
  scaled_solution: True
  T_in: 10
  T_out: 100
  max_dset: null
  only_first: False

model:
  layers: [16, 24, 24, 32, 32]
  modes1: [15, 12, 9, 9]
  fc_dim: 128
  activation: gelu
  output_activation: sigmoid

train:
  device: null
  batchsize: 20
  epochs: 500
  milestones: [100, 200, 300, 400, 500]
  base_lr: 0.001
  scheduler_gamma: 0.5
  save_path: 'models/openloop.pt'
  train_test_split: 0.1
  use_tqdm: True



test:
  eval_train: False
  save_dir: 'results/openloop'
